sources:
  - name: daatbricks_source
    database: dbt  
    schema: dbt_source  
    tables:
      - name: fact_sales
      - name: fact_refunds
      - name: fact_date
      - name: dim_customers
      - name: dim_products
      - name: dim_orders
