sources:
  - name: daatbricks_source
    database: dbt  
    schema: dbt_source  
    tables:
      - name: fact_sales
        columns:
          - name: sales_id
            data_tests:
              - unique
              - not_null
      - name: fact_returns
      - name: dim_date
      - name: dim_customer
      - name: dim_product
      - name: dim_store
        columns:
          - name: store_name
            data_tests:
              - accepted_values:
                  values: ['MegaMart Manhattan', 'MegaMart Brooklyn', 'MegaMart Austin', 'MegaMart San Jose', 'MegaMart Toronto']
      - name: diamonds
